import { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Activity, Flame, Mic, Play, Radio, Send, ShieldCheck, Skull, Swords, Trophy, Volume2, Vote } from "lucide-react";
import { supabase, hasSupabaseConfig } from "./supabase";

const starterPosts = [
  { id: "seed-1", username: "@BassDestroyer", score: 94, tier: "Nuclear Grade", duration: "4.8s", reactions: 1264 },
  { id: "seed-2", username: "@SilentPressure", score: 87, tier: "Thunderclass", duration: "3.2s", reactions: 804 },
  { id: "seed-3", username: "@RoomTone", score: 61, tier: "Air Strike", duration: "2.1s", reactions: 190 },
];
const starterMessages = [
  { id: "m1", username: "@nocturnal", content: "94 is insane." },
  { id: "m2", username: "@lowfreq", content: "Need a duel after that." },
  { id: "m3", username: "@parisgas", content: "chat is moving crazy tonight" },
  { id: "m4", username: "@void", content: "that waveform is illegal" },
];
function makeWave(score) { return Array.from({ length: 24 }, (_, i) => Math.max(10, Math.min(96, Math.sin(i / 2) * 28 + Math.random() * 60 + score / 3))); }
function tierFromScore(score) { if (score >= 92) return "Nuclear Grade"; if (score >= 80) return "Thunderclass"; if (score >= 68) return "Air Strike"; return "Low Pressure"; }
function Waveform({ score = 70, active }) { const bars = useMemo(() => makeWave(score), [score]); return <div className="waveform">{bars.map((height, i) => <motion.span key={i} animate={active ? { height: [height * 0.35, height, height * 0.5] } : { height: height * 0.6 }} transition={{ duration: 0.85, repeat: active ? Infinity : 0, delay: i * 0.025 }} />)}</div>; }
function ScoreBadge({ score }) { return <div className="scoreBadge"><span>Fart Score</span><strong>{score}</strong></div>; }
function PostCard({ post }) { const [playing, setPlaying] = useState(false); const [reactionBoost, setReactionBoost] = useState(0); return <motion.article layout initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="postCard"><div className="postTop"><div><div className="eyebrow"><Radio size={14} /> Live drop</div><h3>{post.username || "@anonymous"}</h3><p>{post.tier || tierFromScore(post.score || 60)} · {post.duration || "3.4s"}</p></div><ScoreBadge score={post.score || 60} /></div><div className="player"><button className="playButton" onClick={() => setPlaying(!playing)}><Play size={18} fill="currentColor" /></button><Waveform score={post.score || 70} active={playing} /></div><div className="reactions"><button onClick={() => setReactionBoost(reactionBoost + 1)}><Skull size={15} /> {Number(post.reactions || 0) + reactionBoost}</button><button onClick={() => setReactionBoost(reactionBoost + 1)}><Flame size={15} /> Fire</button><button onClick={() => setReactionBoost(reactionBoost + 1)}>☣️ Toxic</button><button className="voteBtn"><Vote size={15} /> Vote</button></div></motion.article>; }
function Leaderboard({ posts }) { const ranked = [...posts].sort((a, b) => (b.score || 0) - (a.score || 0)).slice(0, 5); return <section className="panel"><div className="panelTitle"><h2>Daily top</h2><Trophy size={18} /></div><div className="ranking">{ranked.map((post, index) => <div className="rankRow" key={post.id}><div className="rankLeft"><span className="rankNumber">{index + 1}</span><div><strong>{post.username || "@anonymous"}</strong><p>{post.tier || tierFromScore(post.score || 60)}</p></div></div><b>{post.score}</b></div>)}</div></section>; }
function DuelPanel() { const [a, setA] = useState(214); const [b, setB] = useState(241); const total = a + b; return <section className="panel"><div className="panelTitle"><h2><Swords size={18} /> Duel live</h2><span className="pillLight">Round 2 / 3</span></div><div className="duelGrid"><button onClick={() => setA(a + 1)} className="duelBox"><span>@DeepRoom</span><strong>89</strong><div className="meter"><i style={{ width: `${(a / total) * 100}%` }} /></div><small>{a} votes</small></button><button onClick={() => setB(b + 1)} className="duelBox"><span>@GasDealer</span><strong>91</strong><div className="meter"><i style={{ width: `${(b / total) * 100}%` }} /></div><small>{b} votes</small></button></div><p className="microcopy">Each player gets 3 chances. The global chat votes after every round.</p></section>; }
function ChatPanel({ messages, onSend }) { const [text, setText] = useState(""); function submit() { if (!text.trim()) return; onSend(text.trim()); setText(""); } return <aside className="chatPanel"><div className="chatHeader"><h2>Live chat</h2><p>Everyone in the same room.</p></div><div className="chatMessages">{messages.map((m) => <div className="chatBubble" key={m.id}><span>{m.username || "@anonymous"}</span>{m.content}</div>)}</div><div className="chatInput"><input value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === "Enter" && submit()} placeholder="Say something..." /><button onClick={submit}><Send size={17} /></button></div></aside>; }
export default function App() {
  const [entered, setEntered] = useState(false); const [posts, setPosts] = useState(starterPosts); const [messages, setMessages] = useState(starterMessages); const [loadingDrop, setLoadingDrop] = useState(false); const [error, setError] = useState("");
  const liveCount = useMemo(() => (12842 + posts.length * 23).toLocaleString(), [posts.length]);
  useEffect(() => { if (!hasSupabaseConfig) return; fetchPosts(); fetchMessages(); const postsChannel = supabase.channel("posts-live").on("postgres_changes", { event: "INSERT", schema: "public", table: "posts" }, (payload) => setPosts((prev) => [payload.new, ...prev])).subscribe(); const messagesChannel = supabase.channel("messages-live").on("postgres_changes", { event: "INSERT", schema: "public", table: "messages" }, (payload) => setMessages((prev) => [...prev, payload.new].slice(-60))).subscribe(); return () => { supabase.removeChannel(postsChannel); supabase.removeChannel(messagesChannel); }; }, []);
  async function fetchPosts() { const { data, error } = await supabase.from("posts").select("*").order("created_at", { ascending: false }).limit(40); if (error) { setError(error.message); return; } if (data?.length) setPosts(data); }
  async function fetchMessages() { const { data, error } = await supabase.from("messages").select("*").order("created_at", { ascending: true }).limit(60); if (!error && data?.length) setMessages(data); }
  async function dropAudio() { setError(""); setLoadingDrop(true); const score = Math.floor(58 + Math.random() * 42); const post = { username: "@martin", score, tier: tierFromScore(score), duration: `${(1.4 + Math.random() * 4.8).toFixed(1)}s`, reactions: 0 }; if (!hasSupabaseConfig) { setPosts((prev) => [{ ...post, id: crypto.randomUUID() }, ...prev]); setLoadingDrop(false); return; } const { error } = await supabase.from("posts").insert(post); if (error) setError(error.message); setLoadingDrop(false); }
  async function sendMessage(content) { const message = { username: "@martin", content }; if (!hasSupabaseConfig) { setMessages((prev) => [...prev, { ...message, id: crypto.randomUUID() }]); return; } const { error } = await supabase.from("messages").insert(message); if (error) setError(error.message); }
  if (!entered) return <main className="landing"><div className="orb orbOne" /><div className="orb orbTwo" /><nav className="topNav"><div className="brand"><span><Volume2 size={18} /></span>FARTER</div><div className="navLinks"><a>Live room</a><a>Duels</a><a>Leaderboards</a><a>Verified audio</a></div></nav><section className="hero"><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="livePill"><i /> {liveCount} people live right now</motion.div><motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }}>Humanity's first real-time gas network.</motion.h1><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>Join one global room. Drop verified audio. React, vote, duel, and climb the daily, weekly and monthly rankings.</motion.p><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }} className="heroButtons"><button onClick={() => setEntered(true)} className="primaryBtn">ENTER THE ROOM</button><button onClick={() => setEntered(true)} className="secondaryBtn">View leaderboard</button></motion.div></section></main>;
  return <main className="appShell"><header className="appHeader"><div className="brand"><span><Volume2 size={18} /></span><div>FARTER<small>Global room · {liveCount} live</small></div></div><button onClick={dropAudio} disabled={loadingDrop} className="primaryBtn compact"><Mic size={16} />{loadingDrop ? "Verifying..." : "Drop audio"}</button></header>{error && <div className="errorBox">ERROR: {error}</div>}<div className="gridLayout"><aside className="leftRail"><Leaderboard posts={posts} /><DuelPanel /><section className="panel"><div className="panelTitle"><h2><ShieldCheck size={18} /> AI moderation</h2></div><p className="microcopy">MVP mode: the Fart Score is simulated. Next step: real recording, audio upload, and speech rejection.</p></section></aside><section className="feed"><div className="roomIntro"><div><h1>Global live room</h1><p>One chat. One feed. Everyone live.</p></div><span><Activity size={16} /> Live feed</span></div><AnimatePresence>{posts.map((post) => <PostCard key={post.id} post={post} />)}</AnimatePresence></section><ChatPanel messages={messages} onSend={sendMessage} /></div></main>;
}
